# Generated by Django 5.0.1 on 2026-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
