# Generated by Django 5.0.1 on 2026-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_otpverification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
