# Generated by Django 5.0.1 on 2026-05-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0014_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
